# Generated by Django 6.0 on 2025-12-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('jshshr', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Klinika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzil', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ish_vaqti', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shifokor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=255)),
                ('mutaxassislik', models.CharField(max_length=100)),
                ('jinsi', models.CharField(choices=[('E', 'Erkak'), ('A', 'Ayol')], max_length=1)),
                ('staj', models.IntegerField(default=0)),
                ('rasm_url', models.URLField(blank=True, null=True)),
                ('binoning_qavati', models.IntegerField(blank=True, null=True)),
                ('xona_raqami', models.CharField(blank=True, max_length=10, null=True)),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifokorlar', to='core.klinika')),
            ],
        ),
        migrations.CreateModel(
            name='Navbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbat_vaqti', models.DateTimeField(unique=True)),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Bekor qilingan', 'Bekor qilingan'), ("O'tkazildi", "O'tkazildi")], default='Kutilmoqda', max_length=50)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foydalanuvchi')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbatlar', to='core.shifokor')),
            ],
            options={
                'unique_together': {('shifokor', 'navbat_vaqti')},
            },
        ),
    ]
