# Generated by Django 6.0 on 2025-12-10 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foydalanuvchi',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='klinika',
            options={'verbose_name': 'Klinika', 'verbose_name_plural': 'Klinikalar'},
        ),
        migrations.AlterModelOptions(
            name='navbat',
            options={'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.AlterModelOptions(
            name='shifokor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterUniqueTogether(
            name='navbat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='jshshr',
        ),
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='ish_vaqti',
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='binoning_qavati',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='ism_familiya',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='jinsi',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='narx',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='rasm_url',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='staj',
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='xona_raqami',
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='ism',
            field=models.CharField(default='Nomalum foydalanuvchi', max_length=100),
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='tel_raqam',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='yosh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klinika',
            name='nom',
            field=models.CharField(default='Nomalum Klinika', max_length=200),
        ),
        migrations.AddField(
            model_name='klinika',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klinika',
            name='telefon',
            field=models.CharField(default='000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='navbat',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navbat',
            name='vaqt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='ism',
            field=models.CharField(default='Nomalum shifokor', max_length=100),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='reyting',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='manzil',
            field=models.CharField(default='Manzil mavjud emas', max_length=255),
        ),
        migrations.AlterField(
            model_name='navbat',
            name='shifokor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shifokor'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='klinika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.klinika'),
        ),
        migrations.RemoveField(
            model_name='navbat',
            name='navbat_vaqti',
        ),
        migrations.RemoveField(
            model_name='navbat',
            name='status',
        ),
    ]
