# Generated by Django 6.0 on 2025-12-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_foydalanuvchi_options_alter_klinika_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navbat',
            unique_together={('shifokor', 'vaqt')},
        ),
    ]
