# Generated by Django 6.0 on 2025-12-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_navbat_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekshiruv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tur', models.CharField(choices=[('A', 'Analiz (Tahlil)'), ('T', 'Tibbiy tekshiruv (UZI, MRT, KT)')], default='T', max_length=1)),
            ],
            options={
                'verbose_name': 'Tekshiruv/Analiz',
                'verbose_name_plural': 'Tekshiruvlar/Analizlar',
            },
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='reyting',
        ),
        migrations.AddField(
            model_name='klinika',
            name='ish_vaqti',
            field=models.CharField(default='Du-Sha 08:00-20:00', max_length=100),
        ),
        migrations.AddField(
            model_name='klinika',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='klinika',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='klinika_logolari/'),
        ),
        migrations.AddField(
            model_name='klinika',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='ish_kuni',
            field=models.CharField(default='Dushanba, Seshanba, Chorshanba, Payshanba, Juma', max_length=255),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='ish_staji',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='ish_vaqti',
            field=models.CharField(default='Du-Ju 09:00-17:00', max_length=100),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='jinsi',
            field=models.CharField(choices=[('E', 'Erkak'), ('A', 'Ayol')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='qabul_narxi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='shifokor_rasmlari/'),
        ),
        migrations.CreateModel(
            name='KlinikaTekshiruvNarxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('navbat_kuni', models.IntegerField(default=0)),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tekshiruv_narxlari', to='core.klinika')),
                ('tekshiruv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tekshiruv')),
            ],
            options={
                'verbose_name': 'Klinika Tekshiruv Narxi',
                'verbose_name_plural': 'Klinika Tekshiruv Narxlari',
                'unique_together': {('klinika', 'tekshiruv')},
            },
        ),
    ]
