# Generated by Django 6.0 on 2025-12-12 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tekshiruv_remove_shifokor_reyting_klinika_ish_vaqti_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaxsTasdigi',
            fields=[
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shaxsiy_tasdiq', serialize=False, to='core.foydalanuvchi')),
                ('passport_seriya_raqam', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('jshshir', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tasdiqlangan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shaxsni Tasdiqlash',
                'verbose_name_plural': 'Shaxsni Tasdiqlash',
            },
        ),
        migrations.AlterModelOptions(
            name='foydalanuvchi',
            options={'verbose_name': 'Foydalanuvchi Profili', 'verbose_name_plural': 'Foydalanuvchilar Profil'},
        ),
        migrations.RemoveField(
            model_name='klinika',
            name='owner',
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='ism',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='tel_raqam',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='manzil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='klinikatekshiruvnarxi',
            name='navbat_kuni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='navbat',
            name='vaqt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ish_kuni',
            field=models.CharField(default='Dushanba, Seshanba, Chorshanba, Payshanba, Juma, Shanba', max_length=255),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ish_staji',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ism',
            field=models.CharField(max_length=255),
        ),
    ]
