# Generated by Django 6.0 on 2025-12-12 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shaxstasdigi_alter_foydalanuvchi_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('klinika_admin', 'Klinika Administratsiyasi'), ('super_admin', 'Super Admin'), ('menejer', 'Menejer')], default='klinika_admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profil',
                'verbose_name_plural': 'Admin Profillari',
            },
        ),
    ]
