# Generated by Django 6.0 on 2025-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='klinikatekshiruvnarxi',
            name='qavat',
            field=models.IntegerField(default=1, help_text='Tekshiruv amalga oshiriladigan bino qavati', verbose_name='Laboratoriya/Tekshiruv qavati'),
        ),
        migrations.AddField(
            model_name='klinikatekshiruvnarxi',
            name='xona_raqami',
            field=models.CharField(default='101', help_text='Tekshiruv amalga oshiriladigan xona raqami', max_length=10, verbose_name='Laboratoriya/Xona raqami'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='qavat',
            field=models.IntegerField(default=1, help_text='Shifokor qabul qiladigan bino qavati', verbose_name='Qabul qavati'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='xona_raqami',
            field=models.CharField(default='101', help_text='Shifokor qabul qiladigan xona raqami', max_length=10, verbose_name='Xona raqami'),
        ),
    ]
