# Generated by Django 6.0 on 2025-12-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_klinikatekshiruvnarxi_qavat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofil',
            name='klinika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.klinika', verbose_name="Admin qaysi klinikaga bog'langan"),
        ),
        migrations.AlterField(
            model_name='adminprofil',
            name='rol',
            field=models.CharField(choices=[('klinika_admin', 'Klinika Administratsiyasi'), ('super_admin', 'Super Admin')], default='klinika_admin', max_length=20),
        ),
    ]
