# Generated by Django 6.0 on 2025-12-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminprofil_klinika_alter_adminprofil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlinikaTekshiruvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Tekshiruv nomi')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tekshiruv narxi')),
                ('xona_raqami', models.CharField(blank=True, max_length=10, null=True)),
                ('qavat_raqami', models.SmallIntegerField(blank=True, null=True)),
                ('ish_vaqti', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tekshiruv vaqti oralig'i")),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tekshiruvlar', to='core.klinika')),
            ],
            options={
                'verbose_name': 'Klinika Tekshiruvi/Analizi',
                'verbose_name_plural': 'Klinika Tekshiruvlari/Analizlari',
                'unique_together': {('klinika', 'nom')},
            },
        ),
        migrations.DeleteModel(
            name='KlinikaTekshiruvNarxi',
        ),
        migrations.DeleteModel(
            name='Tekshiruv',
        ),
    ]
