# Generated by Django 6.0 on 2025-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_klinikatekshiruvi_delete_klinikatekshiruvnarxi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifokor',
            name='familiya',
            field=models.CharField(default=1, max_length=100, verbose_name='Familiyasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifokor',
            name='sharif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharifi'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
    ]
