# Generated by Django 6.0 on 2025-12-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shifokor_familiya_shifokor_sharif_alter_shifokor_ism'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_kuni', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('ish_boshlanishi', models.TimeField()),
                ('ish_yakuni', models.TimeField()),
                ('qabul_davomiyligi', models.PositiveIntegerField(default=30, help_text='Har bir bemor uchun ajratilgan vaqt (daqiqa)')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_grafiklari', to='core.shifokor')),
            ],
            options={
                'verbose_name': 'Ish grafigi',
                'verbose_name_plural': 'Ish grafiklari',
                'unique_together': {('shifokor', 'hafta_kuni')},
            },
        ),
    ]
