# Generated by Django 6.0 on 2025-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbat',
            name='tasdiqlangan',
        ),
        migrations.AddField(
            model_name='navbat',
            name='status',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20),
        ),
    ]
