# Generated by Django 6.0 on 2025-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_navbat_tasdiqlangan_navbat_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='kun_boshlanishi',
            field=models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], default=0, verbose_name='Boshlanish kuni'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='kun_tugashi',
            field=models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], default=4, verbose_name='Tugash kuni'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='ish_boshlanishi',
            field=models.TimeField(verbose_name='Ish boshlanishi'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='ish_yakuni',
            field=models.TimeField(verbose_name='Ish yakuni'),
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='hafta_kuni',
        ),
    ]
