# Generated by Django 6.0 on 2025-12-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shifokor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='tushlik_boshlanishi',
            field=models.TimeField(blank=True, default='13:00', null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='tushlik_tugashi',
            field=models.TimeField(blank=True, default='14:00', null=True),
        ),
    ]
