# Generated by Django 6.0 on 2025-12-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workschedule_tushlik_boshlanishi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamOlishKuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('sabab', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabab (masalan: Bayram yoki Kasallik)')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsus_dam_olish', to='core.shifokor')),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
                'unique_together': {('shifokor', 'sana')},
            },
        ),
    ]
