# Generated by Django 6.0 on 2026-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_damolishkuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
