# Generated by Django 6.0 on 2026-01-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_foydalanuvchi_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizNavbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbatlar', to='core.klinikatekshiruvi')),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Analiz Navbati',
                'verbose_name_plural': 'Analiz Navbatlari',
                'unique_together': {('analiz', 'sana', 'vaqt')},
            },
        ),
    ]
