# Generated by Django 6.0 on 2026-01-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_analiznavbat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiznavbat',
            options={'verbose_name': 'Analiz navbati', 'verbose_name_plural': 'Analiz navbatlari'},
        ),
        migrations.AlterField(
            model_name='analiznavbat',
            name='foydalanuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analiz_navbatlari', to='core.foydalanuvchi'),
        ),
    ]
