# Generated by Django 6.0 on 2026-01-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_analiznavbat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun_boshlanishi', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('kun_tugashi', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('ish_boshlanishi', models.TimeField()),
                ('ish_yakuni', models.TimeField()),
                ('tushlik_boshlanishi', models.TimeField(blank=True, null=True)),
                ('tushlik_tugashi', models.TimeField(blank=True, null=True)),
                ('qabul_davomiyligi', models.PositiveIntegerField(default=30, help_text='Har bir analiz uchun vaqt (daqiqada)')),
                ('analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_grafiklari', to='core.klinikatekshiruvi')),
            ],
            options={
                'verbose_name': 'Analiz ish grafigi',
                'verbose_name_plural': 'Analiz ish grafiklari',
            },
        ),
    ]
