# Generated by Django 6.0 on 2026-01-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_analizworkschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizDamOlishKuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('sabab', models.CharField(blank=True, max_length=255, null=True)),
                ('analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam_olish_kunlari', to='core.klinikatekshiruvi')),
            ],
            options={
                'verbose_name': 'Analiz dam olish kuni',
                'verbose_name_plural': 'Analiz dam olish kunlari',
                'unique_together': {('analiz', 'sana')},
            },
        ),
    ]
