# Generated by Django 6.0 on 2026-01-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_analizdamolishkuni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizdamolishkuni',
            name='sabab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabab (Bayram, Texnik tanaffus va h.k.)'),
        ),
    ]
