# Generated by Django 6.0 on 2026-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_analizdamolishkuni_sabab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiznavbat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='navbat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='analiznavbat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='navbat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='analiznavbat',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'kutilmoqda')), fields=('analiz', 'sana', 'vaqt'), name='unique_active_analiz_slot'),
        ),
        migrations.AddConstraint(
            model_name='navbat',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'kutilmoqda')), fields=('shifokor', 'vaqt'), name='unique_active_doctor_slot'),
        ),
    ]
