# Generated by Django 6.0 on 2026-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_analiznavbat_options_alter_navbat_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analiznavbat',
            name='unique_active_analiz_slot',
        ),
        migrations.RemoveConstraint(
            model_name='navbat',
            name='unique_active_doctor_slot',
        ),
        migrations.AlterField(
            model_name='analiznavbat',
            name='status',
            field=models.CharField(choices=[('tasdiqlandi', 'Tasdiqlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='tasdiqlandi', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbat',
            name='status',
            field=models.CharField(choices=[('tasdiqlandi', 'Tasdiqlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='tasdiqlandi', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='analiznavbat',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'tasdiqlandi')), fields=('analiz', 'sana', 'vaqt'), name='unique_active_analiz_slot'),
        ),
        migrations.AddConstraint(
            model_name='navbat',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'tasdiqlandi')), fields=('shifokor', 'vaqt'), name='unique_active_doctor_slot'),
        ),
    ]
