# Generated by Django 6.0 on 2026-01-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_analiznavbat_unique_active_analiz_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='yosh',
        ),
    ]
